server:
    port: 8082
spring:
    application:
        name: nacos-discover #服务名
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848 #nacos地址
                namespace: 3e50a8aa-97d7-4313-b9cd-a6d822cb2614